name: caller-workflow
on:
  workflow_call:
    inputs:
      tf_plan_args:
        description: json list of args '[{"key":"k1","value":"v1"},{"key":"k2","value":"v2"}]'
        required: false
        type: string

jobs:
  terraform-pr:
    runs-on: ubuntu-latest
    steps:
    - name: setup
      run: |
        for arg in $(echo '${{ inputs.tf_plan_args }}' | jq --raw-output '.[]| "-var=\"" + join("=") + "\""');do tfpa=$tfpa" $arg";done
        echo "tf_plan_args=${tfpa}" >> $GITHUB_ENV

    - name: Testing
      id: plan
      run: echo ${{ env.tf_plan_args }}
