name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
    - "sandbox"

jobs:
  testing-workflow:
    uses: ./.github/workflows/called-workflow.yml
    secrets: inherit
    with:
      tf_plan_args: '[{"key":"test1","value":${{ "${{secrets.test1}}" }}}]'


